### ISSUE TITLE
Create a Simple Template for Challenges Page - good first issue

### ISSUE THREAD

**Issue by SoftCircuitFm** [DoonOnthon/SorcererCoderNet#1]
Description:
We're looking for community assistance to create a template for the Challenges.cshtml Razor view in our project. This template will be used to display the content of the Challenges page on our website.

Task: Create a template for the Challenges.cshtml Razor view that includes the basic structure and placeholders for future content.

refer to CONTRIBUTION.MD to find how to fork.

Expected Outcome:

A well-structured Challenges.cshtml view template that follows our project's design guidelines.
The template should include placeholders for different sections of the page, such as challenge listings, descriptions, and other relevant content.
Proper formatting and styling, ensuring the template aligns with the look and feel of our website.
Guidelines:

Please refer to the existing _Layout.cshtml / index.cshtml file and other views for design consistency.
Utilize HTML, CSS, and Razor syntax to create the template.
Feel free to use appropriate Bootstrap classes for styling elements if needed.
You're not required to populate the template with actual challenge data; placeholders are sufficient for this task.

**Comment by medha-ab** [comment]
Hi! I want to work on this issue , Please assign it to me.

**Comment by vaishnavii15** [comment]
Hey!
I'd like to contribute to this project.
I can create Template for the Challenges Page.
