### ISSUE TITLE
Add Free Coding Tutorials and Videos to Resources List

### ISSUE THREAD

**Issue by SoftCircuitFm** [DoonOnthon/SorcererCoderNet#3]
We're excited to encourage newcomers to the open-source community to contribute by creating a beginner-friendly task! Your help is sought to expand our resources list with free coding tutorials, videos, and courses that can benefit learners of all skill levels.

Task: Extend our resources list by adding links to free coding tutorials, videos, and courses. This is a great opportunity for beginners to get acquainted with the contribution process.

Expected Outcome:

A comprehensive resources list enriched with links to high-quality coding tutorials and videos.
An opportunity for beginners to contribute and experience the satisfaction of open-source collaboration.
Enhanced learning opportunities for our community members looking for free educational content.
Guidelines:

Explore the web for reliable and reputable free coding tutorials, video series, and courses.
Accumulate a variety of resources covering different programming languages, frameworks, and skill levels.
Follow the provided template to add new resources to the list.
Repository:
Link to the repository: [Repository Name](https://github.com/YourUserName/YourRepositoryName)

Contributor Guidelines:

Familiarize yourself with our CONTRIBUTING.md guide in the repository for a smooth contribution experience.
Clone the repository to your local machine and create a new branch for your contribution.
Locate and edit the resources list according to the provided template.
Ensure the links you add are accurate and functional.
Submit a pull request with your changes.
Hashtags: #GoodFirstIssue #BeginnerFriendly #OpenSource #CodingEducation #LearningResources

Additional Information:

This issue is an excellent starting point for newcomers to engage in the open-source community and contribute positively to the learning journey of others.
Feel free to ask questions in the comments section if you require any assistance or clarification.
Your participation in this endeavor will not only expand our resources but also empower individuals around the world to learn and grow through coding.

**Comment by KartikayCT** [comment]
Hi!I would like to contribute, can you specify what exactly you are looking for and where do you want the additions to be made.
